# Generated by Django 5.2.4 on 2025-07-08 13:55

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
